version: '3.8'

services:

  smtp-server:
    image: meyanksingh/temp-mail-service
    ports:
      - "25:25"
      - "8000:8000"
    environment:
      - HOST=meyank.me
      - PORT=25
      - LOG_LEVEL=debug
      - HTTP_PORT=8000
      - ALLOWED_ORIGINS=http://localhost:3000,https://mail.meyank.me
    depends_on:
      - redis-server

  redis-server:
    image: redis:latest
    ports:
      - "6379:6379"
    environment: []
